service: servis 

provider:
  name: aws
  runtime: nodejs8.10
  stage: radni
  region: us-east-1
  environment:
    variable1: value1
    testenvime : sikimiki

functions:
  test_jedan:
    handler: handler.test_jedan
    events:
     - http:
         path: jedan/{id}
         method: get
         private: true
         request:
          parameters:
            id: true 
  test_post:
    handler: handler.test_post
    events:
     - http:
         path: postic
         method: post
     
         
